sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  global:
    - secure: 

notifications:
  email: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - export PATH=$HOME/miniconda:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels scikit-learn
  - pip install -r requirements.txt
  - cd ./src
script:
  - py.test --cov-config .coveragerc --cov=qinfer
  - pylint --py3k qinfer/

after_success:
  - coveralls

deploy:
  provider: pypi
  user: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  distributions: "sdist bdist_wheel"
  on:
    tags: true
