name: qinfer
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - ipython
  - future>=0.15
  - matplotlib
  - pytest
  - pytest-cov
  - pytest-xdist
  - coveralls
  - pylint
  - qutip
  - pip:
    # We also add additional tools for plotting.
    - mpltools
